/**
 * EduFlow — Supplemental Seed Script
 *
 * Adds more student users, enrollments, and reviews WITHOUT wiping existing data.
 * Safe to run multiple times — uses skipDuplicates / upsert throughout.
 *
 * Run: npm run db:seed-extra
 */

import { config } from "dotenv";

config({ path: ".env.local" });
config({ path: ".env" });

import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";

import { PrismaClient, Role } from "../src/generated/prisma/client";

const adapter = new PrismaPg({
  connectionString: process.env["DATABASE_URL"]!,
});

const prisma = new PrismaClient({ adapter });

const hash = (plain: string) => bcrypt.hash(plain, 10);

// ---------------------------------------------------------------------------
// New students
// ---------------------------------------------------------------------------

const NEW_STUDENTS = [
  { name: "Liam Walker",     email: "liam@student.dev" },
  { name: "Sophia Bennett",  email: "sophia@student.dev" },
  { name: "Noah Harrison",   email: "noah@student.dev" },
  { name: "Olivia Scott",    email: "olivia@student.dev" },
  { name: "Ethan Coleman",   email: "ethan@student.dev" },
  { name: "Isabella Foster", email: "isabella@student.dev" },
  { name: "James Wright",    email: "james@student.dev" },
  { name: "Mia Turner",      email: "mia@student.dev" },
  { name: "Benjamin Hughes", email: "benjamin@student.dev" },
  { name: "Charlotte Brooks",email: "charlotte@student.dev" },
  { name: "William Powell",  email: "william@student.dev" },
  { name: "Amelia Sanders",  email: "amelia@student.dev" },
  { name: "Lucas Griffin",   email: "lucas@student.dev" },
  { name: "Harper Reed",     email: "harper@student.dev" },
  { name: "Henry Price",     email: "henry@student.dev" },
];

// ---------------------------------------------------------------------------
// Reviews keyed by [studentEmail, courseSlug]
// ---------------------------------------------------------------------------

// Actual slugs from DB (generated by seed.ts slug() function)
const S = {
  react:    "the-complete-react-developer-course-2025",
  nextjs:   "nextjs-15-react-the-complete-developer-guide",
  js:       "javascript-the-advanced-concepts",
  python:   "python-for-machine-learning-data-science-2025",
  dl:       "deep-learning-with-pytorch-zero-to-research",
  aws:      "aws-solutions-architect-complete-certification-guide-2025",
  docker:   "docker-kubernetes-the-practical-production-guide",
  ios:      "ios-app-development-swiftui-zero-to-app-store",
  design:   "ui-ux-design-bootcamp-zero-to-job-ready",
  security: "ethical-hacking-penetration-testing-a-to-z",
  flutter:  "flutter-dart-complete-cross-platform-dev-course",
} as const;

const REVIEWS: Array<{
  studentEmail: string;
  courseSlug: string;
  rating: number;
  body: string;
}> = [
  // React course
  {
    studentEmail: "liam@student.dev",
    courseSlug: S.react,
    rating: 5,
    body: "This course completely transformed how I think about front-end development. The section on custom hooks alone is worth the price. I went from copy-pasting React code to truly understanding it.",
  },
  {
    studentEmail: "sophia@student.dev",
    courseSlug: S.react,
    rating: 5,
    body: "Sarah's teaching style is so clear and methodical. I tried learning React from YouTube videos for months with no luck — finished this course in 3 weeks and immediately started building my own projects.",
  },
  {
    studentEmail: "olivia@student.dev",
    courseSlug: S.react,
    rating: 4,
    body: "Excellent course overall. The project-based approach keeps things practical. I'd love a dedicated section on React Query and data fetching patterns, but the core content is top notch.",
  },
  {
    studentEmail: "isabella@student.dev",
    courseSlug: S.react,
    rating: 5,
    body: "I've taken three React courses and this is by far the best one. The way Sarah explains the rendering model and reconciliation actually made the documentation make sense to me for the first time.",
  },
  {
    studentEmail: "mia@student.dev",
    courseSlug: S.react,
    rating: 5,
    body: "Best investment I've made in my learning this year. The production-ready patterns covered here are exactly what I needed to level up from tutorials to real apps. Highly recommend.",
  },
  {
    studentEmail: "lucas@student.dev",
    courseSlug: S.react,
    rating: 4,
    body: "Great content and very well structured. The context API and state management chapters are gold. Knocking one star only because a couple of videos felt slightly slow — but the knowledge depth makes up for it.",
  },
  {
    studentEmail: "amelia@student.dev",
    courseSlug: S.react,
    rating: 5,
    body: "I was skeptical at first but this genuinely lives up to the hype. The exercises are challenging in the right way and the explanations are crystal clear. Sarah is an outstanding educator.",
  },
  {
    studentEmail: "charlotte@student.dev",
    courseSlug: S.react,
    rating: 5,
    body: "Went through this course while job hunting and it gave me the confidence to nail my React interview questions. Got the job! The components and hooks sections are worth every penny.",
  },

  // Next.js course
  {
    studentEmail: "liam@student.dev",
    courseSlug: S.nextjs,
    rating: 5,
    body: "Server Components finally clicked for me watching this course. The mental model Sarah provides for when to use server vs client components is the clearest explanation I've seen anywhere.",
  },
  {
    studentEmail: "isabella@student.dev",
    courseSlug: S.nextjs,
    rating: 5,
    body: "Worth every penny and more. The deployment and edge networking section is absolutely fantastic — I've already used it on two client projects. A must-have for any Next.js developer.",
  },
  {
    studentEmail: "charlotte@student.dev",
    courseSlug: S.nextjs,
    rating: 4,
    body: "Really solid course. The App Router content is comprehensive and the real-world project ties everything together nicely. My only wish is for more content on testing Next.js apps.",
  },

  // JavaScript course
  {
    studentEmail: "liam@student.dev",
    courseSlug: S.js,
    rating: 5,
    body: "I thought I knew JavaScript well until I took this course. The module on closures and the event loop finally filled in all the gaps I had from years of copying Stack Overflow answers.",
  },
  {
    studentEmail: "charlotte@student.dev",
    courseSlug: S.js,
    rating: 5,
    body: "The design patterns section is absolutely brilliant. Went from junior to confidently writing maintainable, scalable JS code. This is the course I wish existed when I started programming.",
  },
  {
    studentEmail: "lucas@student.dev",
    courseSlug: S.js,
    rating: 4,
    body: "Dense but incredibly rewarding. The performance optimization chapter alone changed how I write loops and handle asynchronous code. Highly recommend for anyone past the beginner stage.",
  },

  // Python ML course
  {
    studentEmail: "sophia@student.dev",
    courseSlug: S.python,
    rating: 5,
    body: "Marcus has a gift for making math intuitive. The linear algebra and statistics refresher chapters are brilliant — I finally understand WHY gradient descent works, not just how to call the function.",
  },
  {
    studentEmail: "noah@student.dev",
    courseSlug: S.python,
    rating: 5,
    body: "The capstone project at the end ties everything together perfectly. I built a sentiment analysis model from scratch and deployed it on Hugging Face. This course genuinely delivers on its promises.",
  },
  {
    studentEmail: "james@student.dev",
    courseSlug: S.python,
    rating: 5,
    body: "I switched careers from accounting to data science using this course as my foundation. The step-by-step approach and quality of explanations is unmatched. Marcus is a world-class educator.",
  },
  {
    studentEmail: "benjamin@student.dev",
    courseSlug: S.python,
    rating: 4,
    body: "Excellent curriculum, very well paced for beginners. The scikit-learn pipelines section is particularly good. I'd love a dedicated chapter on time series, but overall this is phenomenal value.",
  },
  {
    studentEmail: "lucas@student.dev",
    courseSlug: S.python,
    rating: 5,
    body: "Took this after struggling through several other ML courses and finally everything made sense. Marcus explains concepts from first principles before showing you the library API — that approach is game-changing.",
  },

  // Deep Learning course
  {
    studentEmail: "sophia@student.dev",
    courseSlug: S.dl,
    rating: 5,
    body: "Building a transformer from scratch is exactly what I needed to move from 'using AI tools' to 'understanding AI systems'. Marcus's intuition-first approach is world-class. Definitely my favorite course on this platform.",
  },
  {
    studentEmail: "benjamin@student.dev",
    courseSlug: S.dl,
    rating: 5,
    body: "I have a statistics background and even I learned things I didn't expect in this course. The backpropagation chapter with visualizations is the best I've ever seen — beats any textbook I've used.",
  },
  {
    studentEmail: "henry@student.dev",
    courseSlug: S.dl,
    rating: 4,
    body: "Very demanding but completely worth it. The CNN and RNN sections are exceptional. I'd recommend having solid Python skills before starting, but if you do, this will take you very far.",
  },

  // AWS course
  {
    studentEmail: "noah@student.dev",
    courseSlug: S.aws,
    rating: 5,
    body: "Passed my AWS SAA-C03 on the first attempt after finishing this. Priya covers everything in depth and the architecture discussion sections are incredibly valuable beyond just exam prep.",
  },
  {
    studentEmail: "ethan@student.dev",
    courseSlug: S.aws,
    rating: 4,
    body: "Great exam prep and genuinely useful for real AWS work. The VPC and networking chapters are superb. A few sections on newer services like AppSync could be expanded, but this is still a top resource.",
  },
  {
    studentEmail: "james@student.dev",
    courseSlug: S.aws,
    rating: 5,
    body: "Priya explains complex cloud concepts in the most approachable way. The hands-on labs had me actually deploying infrastructure instead of just watching slides. Certification passed, job offer received!",
  },
  {
    studentEmail: "benjamin@student.dev",
    courseSlug: S.aws,
    rating: 5,
    body: "I run a small startup and this course changed how I architect our infrastructure. Beyond the certification angle, the cost optimization and high availability sections are practically invaluable.",
  },
  {
    studentEmail: "william@student.dev",
    courseSlug: S.aws,
    rating: 4,
    body: "Solid, well-structured content. The quizzes at the end of each section are really helpful for retention. The serverless section is excellent — covers Lambda, API Gateway, and Step Functions comprehensively.",
  },
  {
    studentEmail: "harper@student.dev",
    courseSlug: S.aws,
    rating: 5,
    body: "I was self-studying for months before finding this course. The structured learning path is exactly what I needed. Priya's explanations are clear, concise, and always backed up with real-world examples.",
  },

  // Docker & Kubernetes course
  {
    studentEmail: "noah@student.dev",
    courseSlug: S.docker,
    rating: 5,
    body: "Docker finally makes complete sense to me after this course. The shift from 'running containers locally' to 'managing a Kubernetes cluster in production' is handled brilliantly across the chapters.",
  },
  {
    studentEmail: "ethan@student.dev",
    courseSlug: S.docker,
    rating: 5,
    body: "The GitOps with ArgoCD section is pure gold. Our team adopted the pattern from this course and our deployment reliability improved dramatically. Priya clearly has real production experience.",
  },
  {
    studentEmail: "william@student.dev",
    courseSlug: S.docker,
    rating: 4,
    body: "Exactly the right depth. Not too shallow, not overwhelming. The Docker multi-stage build optimization chapter alone saved hours of CI build time at my job. Would love more on Istio service mesh.",
  },

  // iOS course
  {
    studentEmail: "olivia@student.dev",
    courseSlug: S.ios,
    rating: 5,
    body: "I published my first app to the App Store after finishing this course. Alex's teaching is incredibly patient and structured. The CloudKit sync chapter is excellent and not covered well elsewhere.",
  },
  {
    studentEmail: "mia@student.dev",
    courseSlug: S.ios,
    rating: 5,
    body: "Coming from a web background, I was nervous about Swift and iOS. Alex made the transition so smooth. The async/await section maps perfectly to what I knew from JavaScript. Brilliant course.",
  },
  {
    studentEmail: "amelia@student.dev",
    courseSlug: S.ios,
    rating: 5,
    body: "The 4 complete apps you build throughout the course give you an amazing portfolio to show employers. SwiftData feels magical after this course — I understand what it does under the hood.",
  },
  {
    studentEmail: "harper@student.dev",
    courseSlug: S.ios,
    rating: 4,
    body: "Very well structured for beginners. The App Store submission section is invaluable — I had no idea about code signing and provisioning profiles before this. My only gripe is the pace felt slightly slow in the first chapter.",
  },

  // Design & UX course
  {
    studentEmail: "olivia@student.dev",
    courseSlug: S.design,
    rating: 5,
    body: "This course turned me from a developer who hated CSS into someone who genuinely loves building UIs. The design systems section is exceptional — I've used it to create a company-wide component library.",
  },
  {
    studentEmail: "mia@student.dev",
    courseSlug: S.design,
    rating: 5,
    body: "Alex walks you through the entire design process from research to high-fidelity prototypes. The accessibility section goes deeper than any other course I've seen. I use these principles daily.",
  },
  {
    studentEmail: "harper@student.dev",
    courseSlug: S.design,
    rating: 5,
    body: "As a self-taught designer this filled in so many foundational gaps. The typography and color theory modules are beautiful — the concepts stuck because the examples are so good.",
  },

  // Cybersecurity course
  {
    studentEmail: "ethan@student.dev",
    courseSlug: S.security,
    rating: 5,
    body: "The most comprehensive ethical hacking course I've found. The network exploitation and web application pentesting sections are excellent. Lab setups are well documented and the CTF challenges are a blast.",
  },
  {
    studentEmail: "william@student.dev",
    courseSlug: S.security,
    rating: 4,
    body: "Very solid course with real-world tools (Burp Suite, Nmap, Metasploit). The report writing section at the end is something most courses skip but is essential for professional work. Well done.",
  },

  // Flutter course
  {
    studentEmail: "james@student.dev",
    courseSlug: S.flutter,
    rating: 5,
    body: "Flutter with Marcus is a joy. The Bloc pattern section demystified state management for me after struggling with it for weeks. My cross-platform app is now live on both stores — this course made it possible.",
  },
  {
    studentEmail: "amelia@student.dev",
    courseSlug: S.flutter,
    rating: 4,
    body: "Great way to maximize your mobile development ROI — one codebase, two platforms. The animations chapter is especially impressive. Would give 5 stars if the Firebase integration section was more in-depth.",
  },
  {
    studentEmail: "henry@student.dev",
    courseSlug: S.flutter,
    rating: 5,
    body: "I built a freelance income from Flutter after this course. Marcus explains Dart and Flutter simultaneously without making it feel overwhelming. The three complete apps are polished and portfolio-worthy.",
  },
];

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log("🌱  Starting supplemental seed (additive — no data wiped)...\n");

  const defaultPassword = await hash("password123");

  // ── 1. Create new students (skip if email already exists) ─────────────────
  console.log("  → Creating new student users...");
  let created = 0;
  const studentIds: Record<string, string> = {};

  for (const s of NEW_STUDENTS) {
    const existing = await prisma.user.findUnique({
      where: { email: s.email },
      select: { id: true },
    });
    if (existing) {
      studentIds[s.email] = existing.id;
    } else {
      const user = await prisma.user.create({
        data: {
          name: s.name,
          email: s.email,
          hashedPassword: defaultPassword,
          role: Role.STUDENT,
          emailVerified: new Date(),
        },
      });
      studentIds[s.email] = user.id;
      created++;
    }
  }
  console.log(`  ✓ ${created} new students created (${NEW_STUDENTS.length - created} already existed)\n`);

  // ── 2. Fetch published courses by slug ────────────────────────────────────
  console.log("  → Fetching published courses...");
  const courses = await prisma.course.findMany({
    where: { status: "PUBLISHED" },
    select: { id: true, slug: true },
  });
  const courseBySlug = Object.fromEntries(courses.map((c) => [c.slug, c.id]));
  console.log(`  ✓ Found ${courses.length} published courses\n`);

  // ── 3. Enrollments (one per student per course, diverse spread) ───────────
  console.log("  → Creating enrollments...");

  const enrollmentMap: Record<string, string[]> = {
    "liam@student.dev":     [S.react, S.nextjs, S.js],
    "sophia@student.dev":   [S.python, S.dl, S.react],
    "noah@student.dev":     [S.aws, S.docker, S.python],
    "olivia@student.dev":   [S.ios, S.react, S.design],
    "ethan@student.dev":    [S.security, S.aws, S.docker],
    "isabella@student.dev": [S.design, S.react, S.nextjs],
    "james@student.dev":    [S.python, S.aws, S.flutter],
    "mia@student.dev":      [S.react, S.design, S.ios],
    "benjamin@student.dev": [S.dl, S.python, S.aws],
    "charlotte@student.dev":[S.nextjs, S.js, S.react],
    "william@student.dev":  [S.docker, S.aws, S.security],
    "amelia@student.dev":   [S.ios, S.flutter, S.react],
    "lucas@student.dev":    [S.js, S.react, S.python],
    "harper@student.dev":   [S.design, S.ios, S.aws],
    "henry@student.dev":    [S.flutter, S.docker, S.dl],
  };

  const enrollmentData: Array<{ userId: string; courseId: string }> = [];
  for (const [email, slugs] of Object.entries(enrollmentMap)) {
    const userId = studentIds[email];
    if (!userId) continue;
    for (const s of slugs) {
      const courseId = courseBySlug[s];
      if (!courseId) { console.warn(`  ⚠ Course slug not found: ${s}`); continue; }
      enrollmentData.push({ userId, courseId });
    }
  }

  const { count: enrollCount } = await prisma.enrollment.createMany({
    data: enrollmentData,
    skipDuplicates: true,
  });
  console.log(`  ✓ ${enrollCount} new enrollments (${enrollmentData.length - enrollCount} skipped as duplicates)\n`);

  // ── 4. Reviews ────────────────────────────────────────────────────────────
  console.log("  → Creating reviews...");

  const reviewData: Array<{ userId: string; courseId: string; rating: number; body: string }> = [];
  for (const r of REVIEWS) {
    const userId = studentIds[r.studentEmail];
    const courseId = courseBySlug[r.courseSlug];
    if (!userId) { console.warn(`  ⚠ Student not found: ${r.studentEmail}`); continue; }
    if (!courseId) { console.warn(`  ⚠ Course slug not found: ${r.courseSlug}`); continue; }
    reviewData.push({ userId, courseId, rating: r.rating, body: r.body });
  }

  const { count: reviewCount } = await prisma.review.createMany({
    data: reviewData,
    skipDuplicates: true,
  });
  console.log(`  ✓ ${reviewCount} new reviews (${reviewData.length - reviewCount} skipped as duplicates)\n`);

  // ── 5. Recompute denormalized totalStudents ───────────────────────────────
  console.log("  → Recomputing totalStudents...");

  const courseEnrollmentCounts = await prisma.enrollment.groupBy({
    by: ["courseId"],
    _count: { courseId: true },
  });
  await Promise.all(
    courseEnrollmentCounts.map((ce) =>
      prisma.course.update({
        where: { id: ce.courseId },
        data: { totalStudents: ce._count.courseId },
      }),
    ),
  );

  const instructorProfiles = await prisma.instructorProfile.findMany({ select: { id: true } });
  await Promise.all(
    instructorProfiles.map(async (ip) => {
      const count = await prisma.enrollment.count({
        where: { course: { instructorId: ip.id } },
      });
      return prisma.instructorProfile.update({
        where: { id: ip.id },
        data: { totalStudents: count },
      });
    }),
  );
  console.log("  ✓ totalStudents recomputed\n");

  // ── 6. Recompute avgRating ────────────────────────────────────────────────
  console.log("  → Recomputing avgRating...");

  const allCourseIds = await prisma.course.findMany({ select: { id: true } });
  await Promise.all(
    allCourseIds.map(async ({ id }) => {
      const agg = await prisma.review.aggregate({
        where: { courseId: id },
        _avg: { rating: true },
      });
      return prisma.course.update({
        where: { id },
        data: { avgRating: agg._avg.rating },
      });
    }),
  );
  console.log("  ✓ avgRating recomputed\n");

  // ── 7. Summary ────────────────────────────────────────────────────────────
  const totalStudents = await prisma.user.count({ where: { role: Role.STUDENT } });
  const totalEnrollments = await prisma.enrollment.count();
  const totalReviews = await prisma.review.count();

  console.log("──────────────────────────────────────────");
  console.log("✅  Supplemental seed complete!\n");
  console.log(`  Total students:    ${totalStudents}`);
  console.log(`  Total enrollments: ${totalEnrollments}`);
  console.log(`  Total reviews:     ${totalReviews}`);
}

main()
  .catch((e) => {
    console.error("\n❌  Supplemental seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
